export enum AppRoutes {
  ROOT = '/',
  AUTH = '/auth',
  ADD_USDT = '/add-usdt',
  BY_CARD= '/by-card',
  CARDS = '/cards',
  CARDS_UP = '/cards/up',
  CARDS_OPERATION = '/cards/operation',
  FAQ = '/faq',
  KYC = '/kyc',
  LOGOUT = '/logout',
  HEALTH_ERROR = '/health-error',
  LANGUAGE = '/language',
  LOCK = '/lock',
  ONBOARDING = '/onboarding',
  REFERRAL = '/referral',
  REFERRAL_DEPTH = '/referral-depth',
  REFERRAL_OUTPUT = '/referral-output',
  REFERRAL_OPERATION = '/referral-operation',
  REGISTER = '/register',
  REQUEST_CARD = '/request-card',
  USER = '/user',
  WALLET = '/wallet',
  WALLET_OPERATION = '/wallet-operation',
  WALLET_OUTPUT = '/wallet-output',
}

export enum AppRoutesNames {
  CARD_ID = 'cards-id',
  CARD_UP_ID = 'cards-up-id',
  WALLET = 'wallet',
  AUTH = 'auth',
  REGISTER = 'register',
  LOGOUT = 'logout',
}